require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ChapsticksController do

  # This should return the minimal set of attributes required to create a valid
  # Chapstick. As you add validations to Chapstick, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "brand" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ChapsticksController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all chapsticks as @chapsticks" do
      chapstick = Chapstick.create! valid_attributes
      get :index, {}, valid_session
      assigns(:chapsticks).should eq([chapstick])
    end
  end

  describe "GET show" do
    it "assigns the requested chapstick as @chapstick" do
      chapstick = Chapstick.create! valid_attributes
      get :show, {:id => chapstick.to_param}, valid_session
      assigns(:chapstick).should eq(chapstick)
    end
  end

  describe "GET new" do
    it "assigns a new chapstick as @chapstick" do
      get :new, {}, valid_session
      assigns(:chapstick).should be_a_new(Chapstick)
    end
  end

  describe "GET edit" do
    it "assigns the requested chapstick as @chapstick" do
      chapstick = Chapstick.create! valid_attributes
      get :edit, {:id => chapstick.to_param}, valid_session
      assigns(:chapstick).should eq(chapstick)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Chapstick" do
        expect {
          post :create, {:chapstick => valid_attributes}, valid_session
        }.to change(Chapstick, :count).by(1)
      end

      it "assigns a newly created chapstick as @chapstick" do
        post :create, {:chapstick => valid_attributes}, valid_session
        assigns(:chapstick).should be_a(Chapstick)
        assigns(:chapstick).should be_persisted
      end

      it "redirects to the created chapstick" do
        post :create, {:chapstick => valid_attributes}, valid_session
        response.should redirect_to(Chapstick.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved chapstick as @chapstick" do
        # Trigger the behavior that occurs when invalid params are submitted
        Chapstick.any_instance.stub(:save).and_return(false)
        post :create, {:chapstick => { "brand" => "invalid value" }}, valid_session
        assigns(:chapstick).should be_a_new(Chapstick)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Chapstick.any_instance.stub(:save).and_return(false)
        post :create, {:chapstick => { "brand" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested chapstick" do
        chapstick = Chapstick.create! valid_attributes
        # Assuming there are no other chapsticks in the database, this
        # specifies that the Chapstick created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Chapstick.any_instance.should_receive(:update).with({ "brand" => "MyString" })
        put :update, {:id => chapstick.to_param, :chapstick => { "brand" => "MyString" }}, valid_session
      end

      it "assigns the requested chapstick as @chapstick" do
        chapstick = Chapstick.create! valid_attributes
        put :update, {:id => chapstick.to_param, :chapstick => valid_attributes}, valid_session
        assigns(:chapstick).should eq(chapstick)
      end

      it "redirects to the chapstick" do
        chapstick = Chapstick.create! valid_attributes
        put :update, {:id => chapstick.to_param, :chapstick => valid_attributes}, valid_session
        response.should redirect_to(chapstick)
      end
    end

    describe "with invalid params" do
      it "assigns the chapstick as @chapstick" do
        chapstick = Chapstick.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Chapstick.any_instance.stub(:save).and_return(false)
        put :update, {:id => chapstick.to_param, :chapstick => { "brand" => "invalid value" }}, valid_session
        assigns(:chapstick).should eq(chapstick)
      end

      it "re-renders the 'edit' template" do
        chapstick = Chapstick.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Chapstick.any_instance.stub(:save).and_return(false)
        put :update, {:id => chapstick.to_param, :chapstick => { "brand" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested chapstick" do
      chapstick = Chapstick.create! valid_attributes
      expect {
        delete :destroy, {:id => chapstick.to_param}, valid_session
      }.to change(Chapstick, :count).by(-1)
    end

    it "redirects to the chapsticks list" do
      chapstick = Chapstick.create! valid_attributes
      delete :destroy, {:id => chapstick.to_param}, valid_session
      response.should redirect_to(chapsticks_url)
    end
  end

end
